#!/usr/bin/env python3
"""Compare two schema-snapshot files section-by-section.

Detects drift in tables, columns, indexes, constraints, foreign keys,
triggers, functions, custom types, views, comments, grants, and
extensions — by diffing a prod snapshot against a reference snapshot derived
from the schema SQL source-of-truth.

Both snapshot files are produced by DataModel3/export-schema-snapshot.sql.
The reference is generated by DataModel3/generate_reference_snapshot.sh
(applies schema SQL to a throwaway Postgres, then runs the snapshot SQL).

Usage:
    compare_full.py <prod-snapshot>
        Compares <prod-snapshot> against DataModel3/schema-reference.txt.

    compare_full.py <reference-snapshot> <prod-snapshot>
        Compares explicitly against the given reference.

Exit codes:
    0  no drift detected
    1  drift detected
    2  usage error or missing file
"""

import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_REFERENCE = SCRIPT_DIR / "schema-reference.txt"

# Sections whose content is not meaningful to diff: row counts and DB size
# legitimately differ between a fresh-init reference DB and prod. Section
# presence is still verified; only the body is skipped.
IGNORE_CONTENT_KEYS = {
    "TABLE INVENTORY WITH ROW COUNTS",
    "SUMMARY",
}

BANNER_RE = re.compile(r"^=+\s*$")
HEADER_RE = re.compile(r"^\s*\d+\.\s+(.+?)\s*$")
NOISE_RE = re.compile(r"^\s*(\(\d+ rows?\)|\+[-+]+\+)\s*$")
WS_RE = re.compile(r"\s+")


def parse_sections(path: Path) -> dict[str, list[str]]:
    """Split snapshot text into {UPPERCASE_SECTION_NAME: [body_lines]}.

    Section boundaries are the three-line psql banner:
        ==========================
          N. SECTION NAME
        ==========================
    """
    sections: dict[str, list[str]] = {}
    current: str | None = None
    body: list[str] = []
    lines = path.read_text().splitlines()

    i = 0
    while i < len(lines):
        header_match = HEADER_RE.match(lines[i + 1]) if i + 2 < len(lines) else None
        if (
            i + 2 < len(lines)
            and BANNER_RE.match(lines[i])
            and header_match is not None
            and BANNER_RE.match(lines[i + 2])
        ):
            if current is not None:
                sections[current] = body
            current = header_match.group(1).strip().upper()
            body = []
            i += 3
            continue
        if current is not None:
            body.append(lines[i])
        i += 1

    if current is not None:
        sections[current] = body

    return sections


def normalize_body(lines: list[str]) -> list[str]:
    """Normalize a section body into a sorted, deduplicated set of lines.

    Drops blank lines, psql border rows, and '(N rows)' footers.
    Collapses runs of whitespace so aligned-output column padding does not
    produce false diffs.
    """
    out = set()
    for line in lines:
        s = line.rstrip()
        if not s.strip():
            continue
        if NOISE_RE.match(s):
            continue
        out.add(WS_RE.sub(" ", s.strip()))
    return sorted(out)


def should_ignore_content(section_name: str) -> bool:
    return any(key in section_name for key in IGNORE_CONTENT_KEYS)


def diff_sections(
    ref: dict[str, list[str]],
    prod: dict[str, list[str]],
) -> tuple[list[str], list[tuple[str, list[str], list[str]]]]:
    """Return (presence_issues, content_diffs).

    presence_issues: human-readable strings for sections present in only one file.
    content_diffs:   [(section_name, lines_only_in_ref, lines_only_in_prod)]
    """
    presence: list[str] = []
    diffs: list[tuple[str, list[str], list[str]]] = []

    ref_keys = set(ref.keys())
    prod_keys = set(prod.keys())

    for section in sorted(ref_keys - prod_keys):
        presence.append(f"Section in reference only: {section}")
    for section in sorted(prod_keys - ref_keys):
        presence.append(f"Section in prod only: {section}")

    for section in sorted(ref_keys & prod_keys):
        if should_ignore_content(section):
            continue
        ref_body = set(normalize_body(ref[section]))
        prod_body = set(normalize_body(prod[section]))
        if ref_body == prod_body:
            continue
        only_ref = sorted(ref_body - prod_body)
        only_prod = sorted(prod_body - ref_body)
        diffs.append((section, only_ref, only_prod))

    return presence, diffs


def print_diff_lines(label: str, lines: list[str], limit: int = 40) -> None:
    if not lines:
        return
    print(f"  {label} ({len(lines)}):")
    for line in lines[:limit]:
        print(f"    {line}")
    if len(lines) > limit:
        print(f"    ...and {len(lines) - limit} more")


def main() -> int:
    args = sys.argv[1:]
    if len(args) == 1:
        ref_path = DEFAULT_REFERENCE
        prod_path = Path(args[0])
    elif len(args) == 2:
        ref_path = Path(args[0])
        prod_path = Path(args[1])
    else:
        print(f"Usage: {sys.argv[0]} [<reference>] <prod-snapshot>", file=sys.stderr)
        return 2

    if not ref_path.exists():
        print(f"Reference snapshot not found: {ref_path}", file=sys.stderr)
        print(
            f"Generate with: {SCRIPT_DIR / 'generate_reference_snapshot.sh'}",
            file=sys.stderr,
        )
        return 2
    if not prod_path.exists():
        print(f"Prod snapshot not found: {prod_path}", file=sys.stderr)
        return 2

    print(f"Reference: {ref_path}")
    print(f"Prod:      {prod_path}")
    print()

    ref = parse_sections(ref_path)
    prod = parse_sections(prod_path)

    print(f"Reference sections: {len(ref)}")
    print(f"Prod sections:      {len(prod)}")
    print()

    presence, diffs = diff_sections(ref, prod)

    if not presence and not diffs:
        print("No drift detected.")
        return 0

    if presence:
        for msg in presence:
            print(msg)
        print()

    for section, only_ref, only_prod in diffs:
        print(f"== {section} ==")
        print_diff_lines("in reference only", only_ref)
        print_diff_lines("in prod only", only_prod)
        print()

    print(
        f"Drift: {len(diffs)} section(s) with content differences, "
        f"{len(presence)} section presence issue(s)."
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
